// server/src/services/quickbooksMapper.service.js
export const quickBooksMapperService = {
  customerToQbo(customer) {
    return {
      DisplayName: customer.name,
      PrimaryEmailAddr: customer.email ? { Address: customer.email } : undefined,
      PrimaryPhone: customer.phone ? { FreeFormNumber: customer.phone } : undefined,
      Notes: customer.localId ? `VoltFlow customer ${customer.localId}` : 'Created by VoltFlow',
    }
  },

  invoiceToQbo(invoice) {
    const subtotal = invoice.lines.reduce((sum, line) => sum + Number(line.quantity || 1) * Number(line.unitPrice || 0), 0)
    const taxRate = Number(invoice.taxRate || 0)

    return {
      CustomerRef: invoice.quickBooksCustomerId ? { value: invoice.quickBooksCustomerId } : undefined,
      CustomerMemo: { value: `VoltFlow job ${invoice.jobId || 'N/A'} | Technician: ${invoice.technician || 'N/A'}` },
      TxnDate: invoice.serviceDate,
      PrivateNote: `Generated by VoltFlow. Job ID: ${invoice.jobId || 'N/A'}`,
      Line: invoice.lines.map((line, index) => ({
        Id: String(index + 1),
        DetailType: 'SalesItemLineDetail',
        Amount: Number(line.quantity || 1) * Number(line.unitPrice || 0),
        Description: `${line.description || line.name}${line.type ? ` (${line.type})` : ''}`,
        SalesItemLineDetail: {
          Qty: Number(line.quantity || 1),
          UnitPrice: Number(line.unitPrice || 0),
          ServiceDate: invoice.serviceDate,
        },
      })).concat(taxRate > 0 ? [{
        DetailType: 'DescriptionOnly',
        Description: `Estimated tax handled according to QuickBooks tax settings. Local estimate: $${(subtotal * taxRate).toFixed(2)}`,
      }] : []),
    }
  },

  paymentToReconciliationCandidate(payment) {
    return {
      amount: Number(payment.TotalAmt || payment.amount || 0),
      transactionDate: payment.TxnDate || payment.date,
      invoiceReference: payment.Line?.[0]?.LinkedTxn?.[0]?.TxnId || payment.invoiceId || null,
      quickBooksPaymentId: payment.Id || null,
    }
  },
}
